if (global.debug == true && global.draw_debug == 1)
{
    var hh = 10
    var ww = 600
    draw_set_font(fnt_small)
    draw_set_halign(fa_right)
    draw_set_color(c_black)
    draw_text_transformed((ww - 2), (hh + 2), ("follow: " + string(follow)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 12), ((("real coords: " + string(x)) + ", ") + string(y)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 22), ((("fake coords: " + string(sprite_x)) + ", ") + string(sprite_y)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 32), ((("prev coords: " + string(prevx)) + ", ") + string(prevy)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 42), ("sprite_index: " + string(sprite_index)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 52), ("fake sprite: " + string(sprite)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 62), ("image_index: " + string(image_index)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 72), ("fake subimg: " + string(sprite_subimg)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 82), ("talk_enabled: " + string(talk_enabled)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 92), ("obj_dialoguer exists: " + string(instance_exists(obj_dialoguer))), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 102), ("global.facechoice: " + string(global.facechoice)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 112), ("local facechoice: " + string(facechoice)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 122), ("global.typer: " + string(global.typer)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 132), ("local typer: " + string(typer)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 142), ("f is for friends that do stuff together: " + string(fun)), 1.5, 1.5, 0)
    draw_text_transformed((ww - 2), (hh + 152), ("image_speed: " + string(image_speed)), 1.5, 1.5, 0)
    if (instance_exists(obj_dialoguer) && instance_exists(obj_dialoguer.writer))
    {
        draw_text_transformed((ww - 2), (hh + 162), ("writer stringpos: " + string(obj_dialoguer.writer.stringpos)), 1.5, 1.5, 0)
        draw_text_transformed((ww - 2), (hh + 172), ("writer originalstring: " + string(obj_dialoguer.writer.originalstring)), 1.5, 1.5, 0)
        draw_text_transformed((ww - 2), (hh + 182), ("writer originalstring len: " + string(string_length(obj_dialoguer.writer.originalstring))), 1.5, 1.5, 0)
    }
    draw_set_color(c_red)
    draw_text_transformed(ww, hh, ("follow: " + string(follow)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 10), ((("real coords: " + string(x)) + ", ") + string(y)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 20), ((("fake coords: " + string(sprite_x)) + ", ") + string(sprite_y)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 30), ((("prev coords: " + string(prevx)) + ", ") + string(prevy)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 40), ("sprite_index: " + string(sprite_index)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 50), ("fake sprite: " + string(sprite)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 60), ("image_index: " + string(image_index)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 70), ("fake subimg: " + string(sprite_subimg)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 80), ("talk_enabled: " + string(talk_enabled)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 90), ("obj_dialoguer exists: " + string(instance_exists(obj_dialoguer))), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 100), ("global.facechoice: " + string(global.facechoice)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 110), ("local facechoice: " + string(facechoice)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 120), ("global.typer: " + string(global.typer)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 130), ("local typer: " + string(typer)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 140), ("f is for friends that do stuff together: " + string(fun)), 1.5, 1.5, 0)
    draw_text_transformed(ww, (hh + 150), ("image_speed: " + string(image_speed)), 1.5, 1.5, 0)
    if (instance_exists(obj_dialoguer) && instance_exists(obj_dialoguer.writer))
    {
        draw_text_transformed(ww, (hh + 160), ("writer stringpos: " + string(obj_dialoguer.writer.stringpos)), 1.5, 1.5, 0)
        draw_text_transformed(ww, (hh + 170), ("writer originalstring: " + string(obj_dialoguer.writer.originalstring)), 1.5, 1.5, 0)
        draw_text_transformed(ww, (hh + 180), ("writer originalstring len: " + string(string_length(obj_dialoguer.writer.originalstring))), 1.5, 1.5, 0)
    }
    draw_set_halign(fa_left)
}
