global.entrance = 1
instance_create(0, 0, obj_persistentfader)
if (room == room_torhouse_bathroom)
    room_goto(room_torhouse3)
else if (room == room_tundra9)
    room_goto(room_tundra_mkidintro)
else if (room == room_basement1_final)
    room_goto(room_basement2_final)
else if (room == room_basement2_final)
    room_goto(room_basement3_final)
else if (room == room_basement3_final)
    room_goto(room_basement4_final)
else if (room == room_tundra_mkidintro)
    room_goto(room_tundra_spaghetti)
else if (room == room_asghouse_bathroom)
    room_goto(room_asghouse3)
else if (room == room_ruins5)
{
    if (global.plot > 8.5)
        room_goto(room_ruins6_alt)
    else
        room_goto(room_ruins6)
}
else if (room == room_ruins6_alt)
    room_goto(room_ruins7)
else if (room == room_tundra1)
{
    if (global.plot >= 35)
        room_goto(room_tundra2_alt)
    else
        room_goto(room_tundra2)
}
else if (room == room_tundra2_alt)
    room_goto(room_tundra1)
else if (room == room_asghouse3)
    room_goto(room_asghouse_bathroom)
else if (room == room_water_bhouse_lockers)
    room_goto(room_water_bhouse_sauna1)
else if (room == room_water_bhouse_stairs)
    room_goto(room_water_bhouse_exit)
else if (room == room_water_bhouse_sauna1)
    room_goto(room_water_bhouse_splitpath)
else if (room == room_water_postbhouse)
    room_goto(room_water_undynefinal)
else if (room == room_ruins_homehub)
    room_goto(room_ruins_home_store)
else if (room == room_ruins_home_store)
    room_goto(room_ruins_homehub)
else if (room == room_water21)
    room_goto(room_water_prebhouse)
else if (room == room_water_prebhouse)
    room_goto(room_water_bhouse_outside)
else if (room == room_tundra_teenhangoutroom)
    room_goto(room_tundra_turnbeforeteenhangout)
else if (room == room_fire_cliffview)
    room_goto(room_fire_apron)
else if (room == room_fire_hh_mainhub)
    room_goto(room_fire_hotelfront_2)
else if (room == room_fire_elevator_l1)
    room_goto(room_fire_secrethallway)
else if (room == room_fire_secrethallway)
    scr_load()
else if (room == room_ruins_sewer_end)
    room_goto(room_ruins_sewer_pretrouble)
else if (room == room_ruins_sewer_pretrouble)
    room_goto(room_ruins_sewer_trouble)
else if (room == room_ruins_sewer2)
    room_goto(room_ruins_sewer1)
else if (room == room_fire_core_roadblock)
    room_goto(room_fire_core_branch)
else if (room == room_fire_core_laserfun)
    room_goto(room_fire_core_branch)
else if (room == room_water13)
    room_goto(room_water_mushroom)
else if (room == room_water_firepuzzle)
    room_goto(room_water8)
else if (room == room_water_mirror)
    room_goto(room_water_firepuzzle)
else if (room == room_water_mushroom)
{
    room_goto(room_water_candy)
    if (global.flag[84] == 2)
        global.flag[84] = 3
}
else if (room == room_water_candy)
    room_goto(room_water_onionsan)
else if (room == room_castle_prebarrier)
{
    if (global.flag[7] == 1)
        room_goto(room_castle_trueexit)
    else
        room_goto(room_next(room))
}
else if (room == room_water13)
    room_goto(room_water_mushroom)
else if (room == room_fire_hotelfront_1)
    room_goto(room_fire_hh_entrance)
else if (room == room_outsideworld)
    room_goto(room_castle_trueexit)
else
    room_goto(room_next(room))
