var spr = ((is_real(argument0) && sprite_exists(argument0)) ? argument0 : sprite_index)
var index = (is_real(argument1) ? argument1 : image_index)
var col = (is_real(argument2) ? argument2 : c_black)
var w = sprite_get_width(spr)
var h = sprite_get_height(spr)
var surface = surface_create(w, h)
var outline = surface_create(w, h)
surface_set_target(outline)
draw_clear_alpha((~col), 1)
draw_set_blend_mode(bm_subtract)
draw_sprite(spr, index, 0, 0)
draw_set_blend_mode(bm_normal)
surface_reset_target()
surface_set_target(surface)
draw_clear_alpha(col, 1)
draw_surface(outline, 0, 0)
surface_reset_target()
var out = sprite_create_from_surface(surface, 0, 0, w, h, true, false, 0, 0)
scr_add_temp_sprite(out)
surface_free(surface)
surface_free(outline)
return out;
