demona = "What are you doing?"
demonb = "Looking for secrets?"
demonc = "Don't put your nose where it doesn't belong"
demond = "or else you might learn something you DON'T like."
demone = "Hee hee hee!"
