global.entrance = 4
instance_create(0, 0, obj_persistentfader)
if (room == room_water12)
    room_goto(room_water11)
else if (room == ROOM_MONITOR)
    room_goto(room_fire6A)
else if (room == room_water_firepuzzle)
    room_goto(room_water_mirror)
else if (room == room_fire_lavalake)
    room_goto(room_fire2)
else if (room == room_ruins_home_walkway)
    room_goto(room_ruins18)
else if (room == room_tundra_town)
    room_goto(room_tundra_qcshop_room)
else if (room == room_tundra_qcshop_room)
    room_goto(room_tundra_town)
else if (room == room_water_bhouse_lockers)
    room_goto(room_water_bhouse_outside)
else if (room == room_fire_hh_entrance)
    room_goto(room_fire_hh_mainhub)
else if (room == room_water_bhouse_exit)
    room_goto(room_water_postbhouse)
else
    room_goto(room_next(room_next(room)))
