draw_sprite(spr_shop2_bg, 0, 0, 0)
draw_sprite(spr_gerson_arm, 0, ((xstart - 30) + armx), ((ystart + 24) + (armx / 2)))
draw_sprite(spr_gerson_body, 0, (xstart + 16), (ystart + 40))
draw_sprite(spr_gerson_mouthbottom, 0, (xstart + 12), (ystart + 31))
draw_sprite(spr_gerson_mouthtop, 0, x, y)
draw_sprite(spr_gerson_eyes, global.faceemotion, x, (y + 15))
