global.entrance = 5
instance_create(0, 0, obj_persistentfader)
if (room == room_fire6A)
    room_goto(ROOM_MONITOR)
else if (room == room_water5)
    room_goto(room_water_firepuzzle)
else if (room == room_water_onionsan)
    room_goto(room_water_candy)
else if (room == room_fire2)
    room_goto(room_fire_lavalake)
else if (room == room_ruins_sewer1)
    room_goto(room_ruins17)
else if (room == ROOM_REDACTED)
    game_restart()
else if (room == room_water_shop)
    room_goto(room_water_gersonshop)
else if (room == room_water_bhouse_outside)
    room_goto(room_water_bhouse_lockers)
else if (room == room_fire_hh_mainhub)
    room_goto(room_fire_hh_entrance)
else if (room == room_tundra_turnbeforeteenhangout)
    room_goto(room_tundra4A)
else if (room == room_water_postbhouse)
    room_goto(room_water_bhouse_exit)
else
    room_goto(room_previous(room_previous(room)))
