scr_monstersetup()
image_speed = 0
part1 = obj_troubleboy_hitch_body
mypart1 = instance_create(x, y, part1)
alarm[9] = 8
hurtanim = 0
hurtsound = snd_hurt_hitch
talked = false
whatiheard = -1
attacked = 0
killed = 0
global.heard = 0
takedamage = 0
mercymod = 7
sha = 0
shb = 0
ht = 100
wd = 100
visible = false
praised = 0
progress = 0
hint = 0
mycommand = 0
gotgold = 0
con = 0
atkup = 0
overtime = 1
wheeltut = 0
