scale = 2
norm_height = (sprite_get_height(spr_maincharad) * scale)
spin_height = (sprite_get_height(spr_mainchara_tspin) * scale)
hit_height = (sprite_get_height(spr_mainchara_die_refuse) * scale)
norm_width = (sprite_get_width(spr_maincharad) * scale)
spin_width = (sprite_get_width(spr_mainchara_tspin) * scale)
hit_width = (sprite_get_width(spr_mainchara_die_refuse) * scale)
spin_offsetx = 6
spin_offsety = 2
hit_offsetx = 30
hit_offsety = 0
spin_timer = 0
act_timer = 0
hit_timer = 0
hit_start = 7
hit_end = 10
hit_ind = 0
hit_dir = 0
hit = 0
act = 0
w = 160
h = 100
posechoose = 0
actdraw = 0
