global.entrance = 2
instance_create(0, 0, obj_persistentfader)
room_goto(room_previous(room))
if (room == room_water_mushroom)
    room_goto(room_water13)
if (room == room_basement2_final)
    room_goto(room_basement1_final)
if (room == room_basement3_final)
    room_goto(room_basement2_final)
if (room == room_ruins7)
{
    if (global.plot > 8.5)
        room_goto(room_ruins6_alt)
    else
        room_goto(room_ruins6)
}
if (room == room_ruins6_alt)
    room_goto(room_ruins5)
if (room == room_tundra3)
{
    if (global.plot >= 35)
        room_goto(room_tundra2_alt)
    else
        room_goto(room_tundra2)
}
if (room == room_tundra2_alt)
    room_goto(room_tundra3)
if (room == room_basement4_final)
    room_goto(room_basement3_final)
if (room == room_tundra_turnbeforeteenhangout)
    room_goto(room_tundra_teenhangoutroom)
if (room == room_tundra_spaghetti)
    room_goto(room_tundra_mkidintro)
if (room == room_tundra_mkidintro)
    room_goto(room_tundra9)
if (room == room_water_mirror)
    room_goto(room_water_firepuzzle)
if (room == room_water_bhouse_outside)
    room_goto(room_water_prebhouse)
if (room == room_water_bhouse_sauna1)
    room_goto(room_water_bhouse_lockers)
if (room == room_water_bhouse_splitpath)
    room_goto(room_water_bhouse_sauna1)
if (room == room_ruins_home_walkway)
    room_goto(room_ruins_homehub)
if (room == room_ruins_homehub)
    room_goto(room_ruins_home_walkway)
if (room == room_torhouse3)
    room_goto(room_torhouse_bathroom)
if (room == room_fire_hh_entrance)
    room_goto(room_fire_hotelfront_1)
if (room == room_fire_apron)
    room_goto(room_fire_cliffview)
if (room == room_fire_elevator_r3)
    room_goto(room_fire_spin)
if (room == room_water_prebhouse)
    room_goto(room_water21)
if (room == room_fire_secrethallway)
    room_goto(room_fire_elevator_l1)
if (room == room_ruins_sewer_pretrouble)
    room_goto(room_ruins_sewer_end)
if (room == room_ruins_sewer_trouble)
    room_goto(room_ruins_sewer_pretrouble)
if (room == room_ruins_sewer1)
    room_goto(room_ruins_sewer2)
if (room == room_fire_core_roadblock)
    room_goto(room_fire_core_laserfun)
if (room == room_fire_core_branch)
    room_goto(room_fire_core_laserfun)
if (room == room_water_bhouse_exit)
    room_goto(room_water_bhouse_stairs)
if (room == room_water_undynefinal)
    room_goto(room_water_postbhouse)
if (room == room_fire_hotelfront_2)
    room_goto(room_fire_hh_mainhub)
if (room == room_asgoreroom)
    room_goto(room_asghouse3)
if (room == room_outsideworld)
    room_goto(room_end_castroll)
if (room == room_asghouse3)
    room_goto(room_asgoreroom)
