event_user(0)
global.interact = 3
instance_create(0, 0, obj_persistentfader)
if (room == room_ruins_sewer_tease)
    room_goto(room_ruins_sewer_end)
else if (room == room_ruins_sewer_end)
    room_goto(room_ruins_sewer_tease)
else if (room == room_ruins_sewer3)
    room_goto(room_ruins_sewer_ladder1)
else if (room == room_ruins_sewer_ladder1)
    room_goto(room_ruins_sewer3)
else if (room == room_ruins_sewer4)
    room_goto(room_ruins_sewer_switchpuzz)
else if (room == room_ruins_sewer_switchpuzz)
    room_goto(room_ruins_sewer4)
else if (room == room_fire_hh_mainhub)
    room_goto(room_fire_hh_lower)
else if (room == room_fire_hh_lower)
    room_goto(room_fire_hh_mainhub)
else
    room_restart()
