global.entrance = 5
instance_create(0, 0, obj_persistentfader)
room_goto(room_previous(room_previous(room)))
if (room == room_water_onionsan)
    room_goto(room_water_candy)
if (room == room_water_candy)
    room_goto(room_water_mushroom)
if (room == room_ruins_sewer3)
    room_goto(room_ruins_sewer4)
if (room == room_fire2)
    room_goto(room_fire_lavalake)
if (room == room_tundra3)
{
    if (global.plot >= 35)
        room_goto(room_tundra2_alt)
    else
        room_goto(room_tundra2)
}
if (room == room_tundra2_alt || room == room_tundra2)
    room_goto(room_tundra3)
if (room == room_fire6A)
    room_goto(ROOM_MONITOR)
if (room == room_fire_spin)
    room_goto(room_fire_hotelfront_1)
if (room == room_fire_hh_mainhub)
    room_goto(room_fire_hh_entrance)
if (room == room_water5)
    room_goto(room_water_firepuzzle)
if (room == room_tundra_town)
    room_goto(room_tundra_town2)
if (room == room_tundra_inn_2f_real)
    room_goto(room_tundra_inn_1f)
if (room == room_fire_hh_shortcut)
    room_goto(room_fire_hh_mainhub)
if (room == room_tundra3A)
    room_goto(room_tundra_teenhangoutroom)
if (room == room_tundra_town2)
    room_goto(room_tundra_town)
if (room == room_tundra_snowpuzz)
    room_goto(room_tundra_xoxopuzz)
if (room == room_tundra_xoxopuzz)
    room_goto(room_tundra_snowpuzz)
if (room == room_fire_core_topleft)
    room_goto(room_fire_core_left)
if (room == room_fire_core_left)
    room_goto(room_fire_core_topleft)
if (room == room_ruins_sewer_tease)
    room_goto(room_ruins10)
if (room == room_ruins_sewer3)
    room_goto(room_ruins_sewer2)
if (room == room_ruins_sewer1)
    room_goto(room_ruins17)
if (room == room_tundra4A)
    room_goto(room_tundra4)
if (room == room_fire_core1)
    room_goto(room_fire_core_controlroom)
if (room == room_tundra_turnbeforeteenhangout)
    room_goto(room_tundra4A)
if (room == room_tundra_lake)
    room_goto(room_tundra_spaghetti)
if (room == room_water_shop)
    room_goto(room_water_gersonshop)
if (room == room_water_bhouse_outside)
    room_goto(room_water_bhouse_lockers)
if (room == room_water_bhouse_splitpath)
    room_goto(room_water_bhouse_cragview)
if (room == room_water_bhouse_stairs)
    room_goto(room_water_bhouse_splitpath)
