x1 = (obj_mainchara.x - 10)
x2 = (obj_mainchara.x + 30)
y1 = (obj_mainchara.y - 5)
y2 = (obj_mainchara.y + 35)
if (!surface_exists(surface))
    surface = surface_create(room_width, room_height)
surface_set_target(surface)
draw_clear_alpha(c_black, 0)
draw_set_alpha(1)
draw_sprite_ext(sprite_index, 0, x1, y1, 1, 1, 0, c_white, 1)
draw_set_blend_mode(bm_subtract)
with (obj_savepoint)
    event_perform(ev_draw, 0)
draw_set_blend_mode(bm_normal)
surface_reset_target()
draw_surface_ext(surface, 0, 0, 1, 1, 0, c_white, glowamt)
