active = false
ossafe_ini_open("undertale.ini")
ini_write_real("Run", "Start", start)
comment = "Ruins"
if (toriel_switch != 0 || force)
    ini_write_real("Run", "TSwitch", toriel_switch)
if (dummy_skip != 0 || force)
    ini_write_real("Run", "RDummy", dummy_skip)
if (rock != 0 || force)
    ini_write_real("Run", "Rock", rock)
comment = "Snowdin"
if (gamer_pixel != 0 || force)
    ini_write_real("Run", "Gamer", gamer_pixel)
if (crossword != 0 || force)
    ini_write_real("Run", "Giasfclfubrehber", crossword)
if (dogi != 0 || force)
    ini_write_real("Run", "Dogi", dogi)
if (geo != 0 || force)
    ini_write_real("Run", "Geo", geo)
if (ice_puzzle != 0 || force)
    ini_write_real("Run", "IcePuzzle", ice_puzzle)
if (igloo != 0 || force)
    ini_write_real("Run", "Igloo", igloo)
comment = "Waterfall"
if (sgs != 0 || force)
    ini_write_real("Run", "SGS", sgs)
if (onionsan != 0 || force)
    ini_write_real("Run", "Onion", onionsan)
if (mkid1 != 0 || force)
    ini_write_real("Run", "MKid1", mkid1)
if (mkid2 != 0 || force)
    ini_write_real("Run", "MKid2", mkid2)
if (dummy_cycles != 0 || force)
    ini_write_real("Run", "Cycle", dummy_cycles)
if (flowerflow != 0 || force)
    ini_write_real("Run", "FF", flowerflow)
if (mkid3 != 0 || force)
    ini_write_real("Run", "MKid3", mkid3)
if (undyne_skip != 0 || force)
    ini_write_real("Run", "Undyne", undyne_skip)
if (undyne_water != 0 || force)
    ini_write_real("Run", "UDWater", undyne_water)
comment = "Hotland - Floor 1"
if (lab_skip != 0 || force)
    ini_write_real("Run", "Lab", lab_skip)
if (pan != 0 || force)
    ini_write_real("Run", "Pan", pan)
if (six_nine != 0 || force)
    ini_write_real("Run", "SixtyNine", six_nine)
if (beowulf != 0 || force)
    ini_write_real("Run", "Beowulf", beowulf)
if (east_west != 0 || force)
    ini_write_real("Run", "EastWest", east_west)
if (jetpack != 0 || force)
    ini_write_real("Run", "Jetpack", jetpack)
comment = "Hotland - Floor 2"
if (guards != 0 || force)
    ini_write_real("Run", "RG", guards)
if (news_skip != 0 || force)
    ini_write_real("Run", "News", news_skip)
comment = "Hotland - Floor 3"
if (north_south != 0 || force)
    ini_write_real("Run", "NorthSouth", north_south)
if (muffet_skip != 0 || force)
    ini_write_real("Run", "Muffet", muffet_skip)
if (play != false || force)
    ini_write_real("Run", "Play", play)
comment = "Hotland - CORE"
if (madjick != 0 || force)
    ini_write_real("Run", "Madjick", madjick)
if (laser_hell != 0 || force)
    ini_write_real("Run", "LaserHell", laser_hell)
if (puzzle_solve != 0 || force)
    ini_write_real("Run", "CorePuzzle", puzzle_solve)
if (puzzle_shots != 0 || force)
    ini_write_real("Run", "CorePuzzleShots", puzzle_shots)
if (snowie_core != 0 || force)
    ini_write_real("Run", "Snowie", snowie_core)
if (mettaton != 0 || force)
    ini_write_real("Run", "MTT", mettaton)
if (alphys != 0 || force)
    ini_write_real("Run", "Alphys", alphys)
comment = "New Home"
if (magolor != 0 || force)
    ini_write_real("Run", "Magolor", magolor)
if (gbs != 0 || force)
    ini_write_real("Run", "GBS", gbs)
if (sans != 0 || force)
    ini_write_real("Run", "Sans", sans)
if (rhombu != 0 || force)
    ini_write_real("Run", "Rhombu", rhombu)
if (quads != 0 || force)
    ini_write_real("Run", "Quads", quads)
comment = "FFFFFF"
if (gang != 0 || force)
    ini_write_real("Run", "Gang", gang)
if (quick_kill != 0 || force)
    ini_write_real("Run", "QuickKill", quick_kill)
ossafe_ini_close()
force = 0
